### ISSUE TITLE
Fix Wallet Connection Methods in wallet.html

### ISSUE THREAD

**Issue by ElrondBuds** [ElrondBuds/ElrondBuds..github.io#1]
## Current Issues
The wallet.html page is experiencing connection issues with multiple wallet types:
- Web wallet connection not functioning
- xPortal mobile connection not working
- Browser extension connection failing
- Ledger hardware connection not operational

### 1. Update Provider Initialization
Update `wallet.js` to properly initialize all wallet providers:

```javascript
// Initialize wallet providers
async function initializeWallet() {
    try {
        console.log('Initializing wallet providers...');
        
        // Initialize network provider with proper configuration
        const networkConfig = {
            chainId: '1', // MultiversX mainnet
            walletAddress: 'https://wallet.multiversx.com',
            apiAddress: 'https://api.multiversx.com'
        };
        
        window.erdjsDapp.MAINNET_CONFIG = networkConfig;
        networkProvider = new erdjsDapp.ProxyNetworkProvider(networkConfig.apiAddress);
        
        // Initialize Web Wallet provider
        webWalletProvider = new erdjsDapp.WebWalletProvider();
        await webWalletProvider.init();
        
        // Initialize Extension provider
        if (window.multiversx) {
            extensionProvider = new erdjsDapp.ExtensionProvider();
            await extensionProvider.init();
        }
        
        // Initialize WalletConnect provider for xPortal
        const walletConnectConfig = {
            bridge: 'https://bridge.walletconnect.org',
            projectId: 'YOUR_PROJECT_ID', // TODO: Add your WalletConnect project ID
            chainId: 1
        };
        walletConnectProvider = new erdjsDapp.WalletConnectProvider(walletConnectConfig);
        await walletConnectProvider.init();
        
        // Initialize Ledger provider (only on HTTPS)
        if (window.location.protocol === 'https:') {
            ledgerProvider = new erdjsDapp.LedgerProvider();
            await ledgerProvider.init();
        }
        
        showStatus('All wallet providers initialized successfully', 'success');
    } catch (error) {
        console.error('Failed to initialize wallet:', error);
        showStatus(`Initialization error: ${error.message}`, 'error');
    }
}
```

### 2. Add Enhanced Error Handling
Add better error handling in `wallet.js`:

```javascript
function showDetailedError(error, context) {
    let message = `${context} failed: `;
    
    if (error.message.includes('not initialized')) {
        message += 'Service not available. Please try again later.';
    } else if (error.message.includes('user rejected')) {
        message += 'Connection was cancelled.';
    } else if (error.message.includes('timeout')) {
        message += 'Connection timed out. Please try again.';
    } else if (error.message.includes('extension not found')) {
        message += 'Please install the MultiversX DeFi Wallet extension.';
    } else {
        message += error.message;
    }
    
    showStatus(message, 'error');
    console.error(`${context} error:`, error);
}
```

### 3. Update Dependencies
Update the wallet.html file to include the latest dependencies:

```html
<!-- MultiversX SDK dependencies -->
<script src="https://cdn.multiversx.com/erdjs-dapp/latest/erdjs-dapp.js"></script>
<script src="https://cdn.multiversx.com/erdjs/latest/erdjs.js"></script>
<!-- WalletConnect dependency -->
<script src="https://unpkg.com/@walletconnect/web3-provider@1.7.1/dist/umd/index.min.js"></script>
<!-- Your wallet implementation -->
<script src="wallet.js"></script>
```

### 4. Add Status Container
Add a status container to wallet.html for better user feedback:

```html
<div id="status-container" class="status-message" style="display: none;">
    <p id="status-text"></p>
    <button onclick="hideStatus()" class="dismiss-button">Dismiss</button>
</div>
```

### 5. Add CSS for Status Messages
Add the following CSS to your styles:

```css
.status-message {
    position: fixed;
    top: 20px;
    right: 20px;
    padding: 15px;
    border-radius: 5px;
    z-index: 1000;
    max-width: 400px;
}

.status-success {
    background-color: #d4edda;
    color: #155724;
    border: 1px solid #c3e6cb;
}

.status-error {
    background-color: #f8d7da;
    color: #721c24;
    border: 1px solid #f5c6cb;
}

.status-loading {
    background-color: #e2e3e5;
    color: #383d41;
    border: 1px solid #d6d8db;
}

.dismiss-button {
    margin-top: 10px;
    padding: 5px 10px;
    border-radius: 3px;
    border: 1px solid currentColor;
    background: transparent;
    cursor: pointer;
}
```

### Required Actions

1. Register for a WalletConnect project ID at https://cloud.walletconnect.com/
2. Replace `'YOUR_PROJECT_ID'` in the WalletConnect configuration
3. Ensure the site is served over HTTPS for Ledger support
4. Update all dependencies to their latest versions
5. Test each connection method after implementation

## Testing Steps

1. Test Web Wallet Connection:
   - Click "Connect Web Wallet"
   - Verify redirect to MultiversX Web Wallet
   - Confirm successful connection

2. Test xPortal Mobile:
   - Click "Connect xPortal"
   - Verify QR code display
   - Test scanning with xPortal app

3. Test Browser Extension:
   - Install MultiversX DeFi Wallet extension
